<?php

$data = [
    "L'IUT de Paris" => array("L’IUT de Paris, situé dans le 16ᵉ arrondissement de Paris, est un institut universitaire de technologie de l'université de Paris, créé en 1968. Il comprend six départements d’enseignement dans les domaines du commerce, de la communication, de la gestion, de l’informatique, du social et de la statistique décisionnelle.", array(48.84186, 2.266185)),
    "La Tour Eiffel" => array("La tour Eiffel est une tour de fer puddlé de 324 mètres de hauteur située à Paris, à l’extrémité nord-ouest du parc du Champ-de-Mars en bordure de la Seine dans le 7ᵉ arrondissement. Son adresse officielle est 5, avenue Anatole-France.", array(48.8583736, 2.2922926)),
    "Le Sacré-Cœur" => array("La basilique du Sacré-Cœur de Montmartre, dite du Vœu national, située au sommet de la butte Montmartre, dans le quartier de Clignancourt du 18ᵉ arrondissement de Paris, est un édifice religieux", array(48.8867081, 2.3409156)),
    "Times Square" => array("Times Square est un quartier de la ville de New York, situé dans l'arrondissement de Manhattan, qui tire son nom de l'ancien siège du New York Times.", array(40.7579787,-73.9877313)),
    "Le Chrysler Building" => array("Le Chrysler Building est un gratte-ciel de la ville de New York, aux États-Unis. Il se dresse à l’intersection de la Lexington Avenue et de la 42ᵉ rue, dans le quartier de Midtown au sud de l'arrondissement de Manhattan.", array(40.7516248,-73.9776907)),
    "La Grande Muraille" => array("Entre le courage et l'effroi, l'humanité et la monstruosité, il existe une frontière qui ne doit en aucun cas céder. William Garin, un mercenaire emprisonné dans les geôles de la Grande Muraille de Chine, découvre la fonction secrète de la plus colossale des merveilles du monde.", array(40.4319118, 116.5681862)),
    "La Cité de Pétra" => array("Créée dans l'Antiquité, vers la fin du viiie siècle av. J.-C., par les Édomites, elle est ensuite occupée vers le vie siècle av. J.-C. par les Nabatéens qui la font prospérer grâce à sa position sur la route des caravanes transportant l'encens, les épices et d'autres produits précieux entre l'Arabie du Sud, l'Égypte, la Syrie et la Méditerranée.", array(30.328459, 35.4421735)),
    "La Statue du Christ Rédempteur" => array("Le Christ Rédempteur est une grande statue du Christ dominant la ville de Rio de Janeiro au Brésil, du haut du mont du Corcovado. Elle est devenue au fil des ans un des emblèmes reconnus internationalement de la ville, au même titre que le Pain de Sucre, la plage de Copacabana ou le carnaval.", array(-22.951911,-43.2126759)),
    "Le Machu Picchu" => array("Le Machu Picchu est une citadelle inca installée en hauteur, dans les montagnes des Andes, au Pérou, au-dessus de la vallée de la rivière Urubamba. Construite au XVe siècle et abandonnée par la suite, elle est réputée pour ses murs en pierres sèches dont la conception sophistiquée associe des blocs immenses sans mortier, le tout formant des bâtiments fascinants qui tirent parti des alignements astronomiques et offrent une vue panoramique.", array(-13.163136,-72.5471516)),
    "Le site archéologique de Chichén Itzá" => array("Chichén Itzá est un complexe mondialement connu de ruines mayas situé dans la péninsule du Yucatán, au Mexique. Une immense pyramide à degrés, appelée El Castillo, domine les 6,5 km² de l'ancienne cité, qui a prospéré d'environ 600 ap. J.-C. jusqu'au XIIIe siècle. Des sculptures graphiques en pierre peuvent être observées sur diverses structures comme le terrain du jeu de balle, le temple des guerriers et le mur des crânes.", array(20.6787867,-88.5706656)),
    "Le Colisée" => array("Le Colisée, à l'origine amphithéâtre Flavien, est un immense amphithéâtre ovoïde situé dans le centre de la ville de Rome, entre l'Esquilin et le Cælius, le plus grand jamais construit dans l'Empire romain. Il est l'une des plus grandes œuvres de l'architecture et de l'ingénierie romaines.", array(41.8902142,12.4900422)),
    "Le Taj Mahal" => array("Sa construction commence en 1632. Cependant, il demeure une incertitude sur la date exacte de la fin des travaux. Le chroniqueur officiel de Shâh Jahân, Abdul Hamid Lahori indique que le Taj Mahal est achevé à la fin de 1643 ou au début de 1644. Mais à l'entrée principale une inscription indique que la construction s'est achevée en 1648. L'État de l'Uttar Pradesh, qui a célébré officiellement le 350e anniversaire de l'édifice en 2004", array(27.1751496,78.0399535))
];

echo json_encode($data);

